### ISSUE TITLE
present a file-like interface to blobs

### ISSUE THREAD

**Issue by glyph** [ghaering/pysqlite#101]
http://www.sqlite.org/c3ref/blob_open.html and http://www.sqlite.org/c3ref/blob_write.html allow users to incrementally write large objects, which can (at least in principle) allow for smaller memory footprint when processing large blob storage requests.  Given that sqlite supports 64-bit blobs, i.e. larger than would fit in memory, this is necessary to be able to access all of its functionality.

**Comment by rogerbinns** [comment]
@glyph your 64 bit portion is not correct.  The default maximum blob size is 1GB.  The maximum you can make it by raising limits is a few bytes shy of 2GB.  This applies to 32 and 64 bit versions of SQLite and is from the file format.

Blobs also have several restrictions.  For example you cannot change their length with the blob I/O interface.  (You can use zeroblob to create one of the right size, and then overwrite portions of that.)  I recommend having a look at the APSW doc to get an idea of a file like API will look like, and the various quirks:  https://rogerbinns.github.io/apsw/blob.html#blob-class

**Comment by glyph** [comment]
@rogerbinns thanks for all that information.  I suppose the interface here is just for limiting memory usage during a bulk load of a large file, not actually for doing things like having a log file that can be appended to inside the database.  Still, it's useful to have :)

**Comment by palaviv** [comment]
hi @glyph you may want to look at pull request #93.

**Comment by captain-cavemaaaan** [comment]
STM this is not the right way to do it. The current "buffer" interface is fine, it should just use blob_read/write behind the scenes; i.e., blob[x:y] should call blob_read to get the result, instead of loading the whole blob into an in-memory buffer; blob[x:y]=foo should call blob_write and update the database.

**Comment by ghaering** [comment]
This project is feature complete and in maintenance-only mode, nothing new will be implemented here. Closing.
