### ISSUE TITLE
Using quotes with ? substitution causes "Incorrect number of bindings supplied" error

### ISSUE THREAD

**Issue by rednebmas** [ghaering/pysqlite#108]
This error description is inaccurate.  

See the following question for more: http://stackoverflow.com/q/1005552/337934

**Comment by rogerbinns** [comment]
pysqlite is correct.  Bindings are recognised by SQLite.  pysqlite provides the unaltered query text to SQLite.  If SQLite accepts it, then pysqlite asks how many bindings there are.

In this case the ? is in quotes and hence is not a binding.  But bindings were provided.  So zero were needed, and one was provided.  Or in other words "Incorrect number of bindings supplied".

pysqlite checks that the number in the statement and the number provided matches.  This is patterned after how python checks in a similar situation - try doing string interpolation (%) with too many or too few.

**Comment by rednebmas** [comment]
Ok, my bad! Thanks for the explanation.
