### ISSUE TITLE
sqlite3. connect() crashes from Process on Python 3

### ISSUE THREAD

**Issue by HaraldNordgren** [ghaering/pysqlite#110]
I am trying to initialize my database from from a process but I get return code `-11`, which seems to be segmentation fault.

```python
import requests
import sqlite3
from multiprocessing import Process


def initializer():
    print("Before sqlite connect")
    connection = sqlite3.connect("/tmp/files.db")

    print("Before sqlite cursor")
    connection.cursor()


if __name__ == "__main__":
    response = requests.get("http://google.com")

    init_process = Process(target=initializer)
    init_process.start()
    init_process.join()

    print("Exit code: %d" % init_process.exitcode)
```

The process crashes before I can create the cursor:

```
 % python3 main.py
Before sqlite connect
Exit code: -11
```

It only happens on Python 3. And *only* if I use `requests` before initializing Sqlite.

I don't have the opportunity to switch to Python 2 -- nor do I really want to.

**Comment by HaraldNordgren** [comment]
Seems to be isolated to Mac OS X. But the problem appears on Python 3.2, 3.4, 3.5, 3.6 there.

Ran this example on CentOS and it worked.

**Comment by rogerbinns** [comment]
This is discussed on the python-sqlite group.  In short you have to be **very** careful when using fork as multiprocessing does.  https://groups.google.com/forum/#!topic/python-sqlite/OGrwjjOqNSc

**Comment by HaraldNordgren** [comment]
I ran the example on a new MacBook with Python 3.6.1, and now there was no problem.

I don't have access to the old machine anymore, so I'm not sure if it persists. But I guess I'll close this one.
