### ISSUE TITLE
type_name is missing in .description cursor attribute

### ISSUE THREAD

**Issue by olsonjosh** [ghaering/pysqlite#112]
Running into issues querying column data types from an sqlite DB using Python. Looks like the sqlite3 library is missing a feature from the Python DB API.

_"The sqlite3 module was written by Gerhard Häring. It provides a SQL interface compliant with the DB-API 2.0 specification described by PEP 249."_

**[sqlite3](https://docs.python.org/2/library/sqlite3.html)**
**.description** "This read-only attribute provides the column names of the last query. To remain compatible with the Python DB API, it returns a 7-tuple for each column where the last six items of each tuple are None."

**[DB-API 2.0](https://www.python.org/dev/peps/pep-0249/)**
**.description** "The first two items ( name and type_code ) are mandatory, the other five are optional and are set to None if no meaningful values can be provided."

**Comment by ghaering** [comment]
pysqlite makes great effort to be compatible with the DB-API 2.0. Too much, in retrospect. But it cannot give you any more information than the underyling engine provides. Which is why you won't get type names.
