### ISSUE TITLE
Python3.6

### ISSUE THREAD

**Issue by outoftrun** [ghaering/pysqlite#116]
When attempting to run flasky under Python3.6 I get a consistent problem with pysqlite2 warning no module by that name is available  I have tried various versions of sqlachemy all with the same problem. This may be an alchemy problem only indirectly related to flasky

Nick

**Comment by jaypeedevlin** [comment]
@outoftrun [As per the python docs](https://docs.python.org/3/library/sqlite3.html) the module is `sqlite3`

```
Python 3.6.0 (v3.6.0:41df79263a11, Dec 22 2016, 17:23:13)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
>>>
```
