### ISSUE TITLE
could the sqlite file be opened in read only mode?

### ISSUE THREAD

**Issue by Jiangshan00001** [ghaering/pysqlite#120]
the easiest one as I could understand,
 could their be another project that named "pysqlitero" to do a read only mode open the sqlite file?

**Comment by berkerpeksag** [comment]
With pysqlite, you can do

```py
import pysqlite2

pysqlite2.connect(..., flags=pysqlite2.SQLITE_OPEN_READONLY)
```

If you use Python 3.4+, you can do

```py
import sqlite3

sqlite3.connect('file:/path/to/database?mode=ro', uri=True)
```

**Comment by Jiangshan00001** [comment]
it works.
thanks!
