### ISSUE TITLE
user-defined function raised exception

### ISSUE THREAD

**Issue by dspublic** [ghaering/pysqlite#121]
Hi,

I've read the pysqlite _pysqlite_func_callback source code, and it looks like the function forwards error into stderr  (traceback) instead of exception. Why sends "user-defined function raised exception" constant message instead of the real exception message?

**Comment by ghaering** [comment]
In case this still helps: https://pysqlite.readthedocs.io/en/latest/sqlite3.html#sqlite3.enable_callback_tracebacks
