### ISSUE TITLE
How do I execute dot directives?

### ISSUE THREAD

**Issue by bk322** [ghaering/pysqlite#129]
How do I execute dot directives:

```
.mode csv
.header on

.once "output.csv"

select
  *
from my_table
;
```

I tried to run it via `conn.executescript` but it doesn't work.

**Comment by bk322** [comment]
Nevermind, seems to be impossible: https://stackoverflow.com/q/2346074/788700

**Comment by rogerbinns** [comment]
There is a possible solution using APSW.  I added an answer on StackOverflow with details.

**Comment by ghaering** [comment]
This is not an SQL feature and only available as part of the sqlite3 commandline tool. Thanks, Roger!
