### ISSUE TITLE
There is no seek function implementation

### ISSUE THREAD

**Issue by biswapatiacharya** [ghaering/pysqlite#130]
I have a need of seek function to move back to certain cursor position after doing fetchall. 

It is an enhancement request for adding seek function to the library.

**Comment by ghaering** [comment]
This is not part of the DB-API. https://www.python.org/dev/peps/pep-0249/#cursor-methods and will thus not be implemented.

**Comment by biswapatiacharya** [comment]
Hey ghaering, sorry for the confusion. 
I was looking for seek function, but the alternate solution I found was "Cursor.scroll(value [, mode='relative' ])" which is there in pep-0249
https://www.python.org/dev/peps/pep-0249/#optional-db-api-extensions
So only was checking for the enhancement request.

Thank You,
biswapatiacharya
