### ISSUE TITLE
expose sqlite3_db_status

### ISSUE THREAD

**Issue by stardust85** [ghaering/pysqlite#131]
Hi,

is sqlite3_db_status avaliable through this wrapper? I need to read information about number of unsatisfied constraints. We need it for django improvement - without it django may never use foreign key checking in sqlite in tests https://code.djangoproject.com/ticket/29928#comment:8

**Comment by berkerpeksag** [comment]
Note that this project only supports Python 2, so even if `sqlite3_db_status` is exposed in pysqlite, Django can't use it :) The better place to report this is https://bugs.python.org/ You can add me to nosy list there (type "berker.peksag" in the "Nosy List" field at https://bugs.python.org/issue?@template=item)

**Comment by stardust85** [comment]
The django bug is finally closed - they found another way how to find the broken transaction :)
