### ISSUE TITLE
[Suggestion] Object passed as parameters

### ISSUE THREAD

**Issue by asparagii** [ghaering/pysqlite#132]
#### Example
```python3
class C(object):
    def __init__(self, field0, field1):
        self.field0 = field0
        self.field1 = field1

obj = C("foo", "bar")
cursor.execute('''SELECT field1 FROM table WHERE field1=:field1''', obj)
```

When you try to do this a `ValueError` is thrown:
```ValueError: parameters are of unsupported type```

#### Proposal
We could use the `__dict__` field of the object internally, instead of having the user to manually pass it as a parameter.

##### Disclaimer
I don't know this library that much and maybe something like this has already been discussed or implemented, in which case I'm sorry I could not find any information about it.

**Comment by MicheleLambertucci** [comment]
From what I understand, even if you define the `__conform__` method you are not able to use named placeholders (`execute('SELECT * WHERE thing = :property', obj)`).

**Comment by ghaering** [comment]
It's a better idea to use an ORM or code a custom solution. I won't even recommend to use __conform__ and friends any longer. This stuff is then never portable anywhere else. My recommendation is to either use plain DB-API or SQLAlchemy.
