### ISSUE TITLE
Geting error:  unrecognized token: "772762303ORDER"

### ISSUE THREAD

**Issue by EyasuTew** [ghaering/pysqlite#135]
unrecognized token: "772762303ORDER"

when I try :
```
for row in c.execute("SELECT * FROM Table where Id="+str(id)+"ORDER BY id"):
    print(row)
```

**Comment by rogerbinns** [comment]
You are not supplying valid SQL.  Print out your query in full first to see.  (It lacks space, and possibly quoting.)  

That said, creating query strings like you did is very dangerous, and is known as [SQL injection](https://en.wikipedia.org/wiki/SQL_injection).  Instead use bindings - you put a **?** in the query and provide the value as a separate argument.  The [documentation](https://docs.python.org/3/library/sqlite3.html) mentions this around the 5th paragraph ("Usually your SQL operations will need to use values from Python variables ...")
