### ISSUE TITLE
sqlite3.OperationalError: near "COLUMN": syntax error

### ISSUE THREAD

**Issue by LokiSharp** [ghaering/pysqlite#136]
sqlite3.OperationalError: near "COLUMN": syntax error

When I try to execute it at Windows 10:
```
statement = f"""ALTER TABLE {table_name}
    RENAME COLUMN {column} TO {new_column};"""
```

But it can execute successful in sqlite cli tool and Python at Linux.

**Comment by ekiefl** [comment]
I believe this is an SQL version error. I receive this error when using `3.31.1`, but not when using `3.30.1`. @LokiSharp what caused you to close this issue?
