### ISSUE TITLE
SQLite to mysql or other

### ISSUE THREAD

**Issue by BedoM** [ghaering/pysqlite#137]
Bonjour,
Je cherche a savoir, si il est possible d'envoyer des DB, ROW, ou TABLE avec l'api python : 

Mon but est de stocker dans une petite base de donée légere (equipement tres peu puissant) et d'envoyer quand du reseau et disponible(based on LTE) de facon  incrementale si possible.

Merci de vos réponses

**Comment by ghaering** [comment]
Please ask support questions on the mailing list. And in English, if at all possible.
