### ISSUE TITLE
What’s the point of this module?

### ISSUE THREAD

**Issue by mcepl** [ghaering/pysqlite#138]
I am sorry, I don’t want to be disrespectful, but what is the difference between this module and [sqlite3](https://docs.python.org/3/library/sqlite3.html) module in the standard library? Why should anybody use it? Could we get couple of lines on this topic to README, please?

**Comment by jaysonlarose** [comment]
From <https://docs.python.org/3.7/library/sqlite3.html>, in "see also":

> <https://github.com/ghaering/pysqlite>
> The pysqlite web page – sqlite3 is developed externally under the name “pysqlite”.

Therefore, this module *is* the sqlite module in the standard library.

Disclaimer: I have nothing to do with the development of Python or pysqlite.

**Comment by mcepl** [comment]
OK, still I would love to have a line like that in README here. Also, “developed” as in “Latest commit e728ffb on 30 Aug 2016”?
