### ISSUE TITLE
The underlying database pointer (sqlite3*) is not exposed.

### ISSUE THREAD

**Issue by jaroslov** [ghaering/pysqlite#139]
On MacOS, the default sqlite3 is not compiled with load-extensions enabled. This means you cannot load virtual table extensions without recompilation of the sqlite3 library. However, if an extension is compiled with the flag -DSQLITE_CORE, then the extension can still be manually loaded by calling the C-entry point to the extension using the c_types interface.

This requires access to the underlying sqlite3* pointer (handle).

Thus, this is a request to expose the sqlite3* database handle to python.

**Comment by rogerbinns** [comment]
This project is not being developed here anymore.  The work is done [within the Python project](https://github.com/python/cpython/tree/master/Modules/_sqlite). This is the original sqlite3 module that ended up in the standard library.

That said, you have two quick options.  APSW provides [this pointer](https://rogerbinns.github.io/apsw/connection.html?highlight=pointer#apsw.Connection.sqlite3pointer) if you want to switch (disclaimer: I am the APSW author).

Alternatively the pointer is the first member of the [PyObject](https://docs.python.org/3/c-api/structures.html?highlight=pyobject#common-object-structures) after the standard header.  You can access the PyObject [in ctypes](https://docs.python.org/3/library/ctypes.html?highlight=pyobject#ctypes.py_object) but will need to do a bit more arithmetic to extract the database pointer.

**Comment by jaroslov** [comment]
Thank you! I used the latter method.
