### ISSUE TITLE
[patch] add tests for save points

### ISSUE THREAD

**Issue by ghaering** [ghaering/pysqlite#18]
_From [rcta...@gmail.com](https://code.google.com/u/110956366953663411409/) on June 11, 2010 16:43:14_

Add two simple tests that utilise the savepoint statements 'savepoint', 'release savepoint' and 'rollback to savepoint'.

Tested on python 2.5.4 and a recent sqlite amalgamation.

**Attachment:** [0000-add-test-for-savepoints.patch](http://code.google.com/p/pysqlite/issues/detail?id=18)

_Original issue: http://code.google.com/p/pysqlite/issues/detail?id=18_

**Comment by rogerbinns** [comment]
They are possibly checking the pysqlite parsing code doesn't get confused by what kind of statement they are when doing implicit transactions.

**Comment by ghaering** [comment]
I think that the real solution to most of weird transaction related issues is 1) switching to the v2 API and 2) using sqlite3_get_autocommit() to look up if SQLite is in a transaction or not
