### ISSUE TITLE
openbsd compilation fix

### ISSUE THREAD

**Issue by ghaering** [ghaering/pysqlite#22]
_From [natanopt...@gmail.com](https://code.google.com/u/109442800513974821768/) on October 05, 2010 16:42:14_

When installing pysqlite on openbsd (4.7/4.8) via pip/easy_install
the compilation fails becasue the sqlite header file is located in a
"non-standard" location. This is because packages are located under the
/usr/local prefix.

Attached is a patch, wich fixes the compilation for openbsd.

**Attachment:** [pysqlite2.6.0_fix_openbsd_build.diff](http://code.google.com/p/pysqlite/issues/detail?id=22)

_Original issue: http://code.google.com/p/pysqlite/issues/detail?id=22_

**Comment by giganteous** [comment]
For future reference:
```
  pip install pysqlite3 --install-option="--with-sqlite=/usr/local"
```
