### ISSUE TITLE
pysqlite treats SAVEPOINT and RELEASE as DDL (nested transactions don't work)

### ISSUE THREAD

**Issue by ghaering** [ghaering/pysqlite#24]
_From [skrulx](https://code.google.com/u/skrulx/) on October 29, 2010 01:11:27_

Nested transactions do not work with pysqlite because the SAVEPOINT and RELEASE statements are not recognized as non-DLL which cause implicit commits to be issued before execution.

Attached is a simple patch that adds "savepoint" and "release" to the list of statements that don't cause an implicit commit.

**Attachment:** [savepoint.patch](http://code.google.com/p/pysqlite/issues/detail?id=24)

_Original issue: http://code.google.com/p/pysqlite/issues/detail?id=24_

**Comment by lrowe** [comment]
I had a copy of @skrul's patch in my google code clone. Applied to a github fork at: lrowe/pysqlite@f53a9f5a151706d0a65840a4493ecd87b70444cf

If you apply it please fix up the authorship information.

**Comment by bkircher** [comment]
Great! Thanks a lot.
