### ISSUE TITLE
Authorizer Action Code Missing: SQLITE_FUNCTION

### ISSUE THREAD

**Issue by ghaering** [ghaering/pysqlite#45]
_From [aau...@gmail.com](https://code.google.com/u/104419119678156473177/) on October 25, 2011 20:43:45_

One authorizer action code is missing from module.c : SQLITE_FUNCTION

Defined here: http://www.sqlite.org/c3ref/c_alter_table.html

_Original issue: http://code.google.com/p/pysqlite/issues/detail?id=45_

**Comment by rogerbinns** [comment]
@ghaering SQLite now publishes a database of all functions, constants etc as https://sqlite.org/toc.db which makes it easy to check that you have included all relevant values.

**Comment by ghaering** [comment]
@rogerbinns Thanks, that's very useful!
