### ISSUE TITLE
When compiling, define SQLITE_ENABLE_FTS3_PARENTHESIS

### ISSUE THREAD

**Issue by ghaering** [ghaering/pysqlite#46]
_From [jcow...@gmail.com](https://code.google.com/u/106517930221342256151/) on December 02, 2011 23:55:36_

What steps will reproduce the problem? 1. Perform a FTS query using the enhanced sytax such as using AND, NOT or PARENS What is the expected output? What do you see instead? Rows matching the enhanced logic What version of the product are you using? On what operating system? 2.6.3 for Windows Python 2.7 Please provide any additional information below. Documentation on this defintion can be found at: http://www.sqlite.org/compile.html#enable_fts3_parenthesis It's benefits can be found at: http://www.sqlite.org/fts3.html#section_3_1

_Original issue: http://code.google.com/p/pysqlite/issues/detail?id=46_

**Comment by ghaering** [comment]
Instead, we now build the fts5 module when using the amalgamation.

**Comment by rogerbinns** [comment]
Note that FTS3 & 4 are stable, but that FTS5 is still currently experimental and subject to change including the table format.  I recommend you enable the SQLITE_ENABLE_FTS3_PARENTHESIS option and FTS 3/4 only until FTS5 is declared stable.
