### ISSUE TITLE
How do I build pysqlite so that it works (OS X, homebrew, virtualenv, spatialite)

### ISSUE THREAD

**Issue by anentropic** [ghaering/pysqlite#60]
I'm trying to use GeoDjango with SQLite/spatialite backend

I have followed [this tutorial](http://www.maurobianchi.it/en/blog/2012/03/16/geodjango-spatialite-osx/) to install everything but when I try to connect to the db I get this error:

_The pysqlite library does not support C extension loading. Both SQLite and pysqlite must be configured to allow the loading of extensions to use SpatiaLite._

From what I've read, that is what commenting out `#define=SQLITE_OMIT_LOAD_EXTENSION` in my `setup.cfg` before building is supposed to fix, but it hasn't.

I also get the following error when I do the last step of the instructions:

```
$ spatialite /tmp/test.db "SELECT InitSpatialMetaData();"
SQLite header and source version mismatch
2013-10-17 12:57:35 c78be6d786c19073b3a6730dfe3fb1be54f5657a
2013-09-03 17:11:13 7dd4968f235d6e1ca9547cda9cf3bd570e1609ef
```

I am guessing perhaps it has built pysqlite against the OS X (10.9) version of sqlite3 rather than the one I installed from homebrew ...?

In which case how do I change the setup.cfg to make it work?

I have tried this but get the same errors:

```
[build_ext]
#define=
#include_dirs=/usr/local/include
library_dirs=/usr/local/Cellar/sqlite/3.8.1/lib
#libraries=sqlite3
#define=SQLITE_OMIT_LOAD_EXTENSION
```

**Comment by ghaering** [comment]
Apparently you guys figured out how to build the features in.
