### ISSUE TITLE
Specify amalgamation url in setup.py for static build

### ISSUE THREAD

**Issue by cilia** [ghaering/pysqlite#62]
In the source code that was hosted on googlecode, inside setup.py, there was a line where you can specify an url pointing to the amalgamation package to use when you do `setup.py build_static`.

In the newer version available on PyPI, this line/option seems to disappear. So is there still a way to specify which amalgamation package to use when compiling pysqlite statically?

**Comment by ghaering** [comment]
No, the build process expects to find the amalgamation files in the pysqlite root directory. The following commands will do the trick:

wget http://www.sqlite.org/snapshot/sqlite-amalgamation-201412311418.zip
unzip sqlite-amalgamation-201412311418.zip
python2.7 setup.py build_static
