### ISSUE TITLE
Missing Enable Load Extension on Build

### ISSUE THREAD

**Issue by anothergisblogsamples** [ghaering/pysqlite#63]
Hello,

According to your help, there should be a function called enable_load_extension(), but after build, I find the function is missing.

I am using python 2.7 with version 2.6.3.

Error: AttributeError: 'pysqlite2.dbapi2.Connection' object has no attribute 'enable_load_extension'

I refer to: https://pysqlite.readthedocs.org/en/latest/sqlite3.html

Thank you

**Comment by a110605** [comment]
I have try above steps in Mac. It's good to call enable_load_extension() with any problem.

But I try same steps on Linux (centOS). Python fails to call enable_load_extension() with same error message 

AttributeError: 'pysqlite2.dbapi2.Connection' object has no attribute 'enable_load_extension'

Any idea?
