### ISSUE TITLE
race condition bug? Bind error on cursor.execute. Second try with exact same vars works. 

### ISSUE THREAD

**Issue by ZeerDonker** [ghaering/pysqlite#64]
Hello,

In a program where multiple times cursors are opened, select and other statements are performed and then closed. 
Some of those select statements fail with the following error. This error does not happen, if the exact same line is executed again, with exactly the same variables. 

```
InterfaceError: Error binding parameter 0 - probably unsupported type.
```

So something like this fails occasionally. (Where the dataStr is more than 160 characters long. )
```python
cursor = conn.cursor()
results = cursor.execute ("SELECT * FROM tableName WHERE Data_One LIKE ? AND is_bla=? AND Data_ola=?;", (dataStr + '%', '1', '8',))
hi = results.fetchone()
cursor.close()
```
And something like this works.
```python
cursor = conn.cursor()
try:
    results = cursor.execute ("SELECT * FROM tableName WHERE Data_One LIKE ? AND is_bla=? AND Data_ola=?;", (dataStr + '%', '1', '8',))
except:
    results = cursor.execute ("SELECT * FROM tableName WHERE Data_One LIKE ? AND is_bla=? AND Data_ola=?;", (dataStr + '%', '1', '8',))
hi = results.fetchone()
cursor.close()
```

**Comment by ghaering** [comment]
I cannot do much without a test case. I am sorry.
