### ISSUE TITLE
Revert SQLITE_OMIT_LOAD_EXTENSION

### ISSUE THREAD

**Issue by chrisspen** [ghaering/pysqlite#66]
Could you please revert https://github.com/ghaering/pysqlite/commit/83b648ae5037d8e0740cfe7996346d906827caa1, that requires removing `define=SQLITE_OMIT_LOAD_EXTENSION` in order to build pysqlite? This may help installation on Mac, but it breaks automatic installation via pip everywhere else, since pip doesn't have the ability to make this edit.

**Comment by ghaering** [comment]
Reverted in a39f33c0a16da4c97c6e4b23173c53518a9e8da5.
