### ISSUE TITLE
Memory leaks when INSERTing with distinct values.

### ISSUE THREAD

**Issue by alibotean** [ghaering/pysqlite#68]
There seems to be significant memory leaks when multiple insert statements are executed with distinct values.

I'm using version `2.6.0` of pysqlite.

Here's a code snippet to outline the problem:

```python
import gc
import objgraph
import sqlite3

connection = sqlite3.connect('./leaks.db3')

cursor = connection.cursor()
cursor.execute('CREATE TABLE test_insert (id ROWID, value INTEGER);')

query = 'INSERT INTO test_insert (value) VALUES (%s)'

gc.collect()
objgraph.show_growth()

for entry in range(1, 2000):
    cursor.execute(query % entry)

connection.commit()

gc.collect()
objgraph.show_growth()

cursor.close()
connection.close()
```

This does not reproduce when using `executemany` or `execute` with a parametrized query.

**Comment by ghaering** [comment]
The difference is that the statement cache is filled in this case. This might appear like a memory leak, but it is just a growing cache.
