### ISSUE TITLE
Cursor.lastrowid always None when using first line SQL comments

### ISSUE THREAD

**Issue by ahawker** [ghaering/pysqlite#70]
**Summary:**
Cursor.lastrowid will always return None when using a SQL comments (-- or /*) in the first line of the statement.

After some debugging, It appears that [detect_statement_type](https://github.com/ghaering/pysqlite/blob/master/src/cursor.c#L41) will return STATEMENT_OTHER when given a statement which contains a SQL comment as the first line. Since the logic in [_pysqlite_query_execute](https://github.com/ghaering/pysqlite/blob/master/src/cursor.c#L750) will only attempt to populate lastrowid when running a single INSERT statement, it is always left as None.

This reproduces on both on both pysqlite2 and sqlite3 baked into Python 2.7.5.

**Steps to Reproduce:**

```
from pysqlite2 import dbapi2 as sqlite3
print sqlite3.version
print sqlite3.sqlite_version

SCHEMA = 'CREATE TABLE IF NOT EXISTS people (first TEXT, last TEXT)'

BAD_SINGLE_LINE_INSERT = '-- This is a comment!\nINSERT INTO people (first, last) VALUES (?, ?)'

BAD_MULTI_LINE_INSERT = """
-- This is a comment
INSERT INTO people (first, last) VALUES (?, ?)
"""

GOOD_SINGLE_LINE_INSERT = 'INSERT INTO people (first, last) VALUES (?, ?)'

def main():
    db = sqlite3.connect(':memory:')
    cursor = db.cursor()
    cursor.execute(SCHEMA)
    cursor.execute(BAD_SINGLE_LINE_INSERT, ('Foo', 'Bar'))
    print cursor.lastrowid
    cursor.execute(BAD_MULTI_LINE_INSERT, ('Foo2', 'Bar2'))
    print cursor.lastrowid
    cursor.execute(GOOD_SINGLE_LINE_INSERT, ('Foo3', 'Bar3'))
    print cursor.lastrowid

if __name__ == '__main__':
    main()
```

**Output:**

```
$python main.py
2.6.3
3.8.7.2
None
None
3

```

**Workaround:**
Minor inconvenience in this case as we can just comment outside of the SQL statements or any position other than the first line.

**Comment by ghaering** [comment]
Fixed in 6128289e0de0476706207cb4dadae54a15cc079d
