### ISSUE TITLE
Python3 is not supported

### ISSUE THREAD

**Issue by jameshiebert** [ghaering/pysqlite#72]
From looking at the code, it's pretty clear that this package does not support Python3. For example, even your setup script still uses print statements [instead of functions](https://docs.python.org/3.0/whatsnew/3.0.html#print-is-a-function) (e.g. [here](https://github.com/ghaering/pysqlite/blob/master/setup.py#L85)) and [raises exceptions with comma separated arguments](https://github.com/ghaering/pysqlite/blob/master/cross_bdist_wininst.py#L86) [which is no longer supported](http://docs.pythonsprints.com/python3_porting/py-porting.html#exceptions).

I don't know if you have plans to support Python3. However, in the mean time, could you at least specify "Programming Language :: Python :: 2" in your trove classifiers to make it clear that 3 is *not* supported?

**Comment by giumas** [comment]
I need to use the R*tree module with Python 3.4 on Window. Can I accomplish this task without have to build Python from source? On Python 2.7 I have simply used the PySqlite setup.py.

**Comment by giumas** [comment]
I have explained what is my issue here: http://stackoverflow.com/q/29751765/2741329

**Comment by jameshiebert** [comment]
I [started a branch](https://github.com/jameshiebert/pysqlite/tree/python3) that deals with the Python3 problems in `setup.py` and `cross_bdist_wininst.py`. But someone else would need to port the C extension [following these instructions](https://docs.python.org/3.4/howto/cporting.html).

**Comment by rsvp** [comment]
@jameshiebert et al. what are some of the difficulties in porting to python3, and the expected timeline? 

Per the googlegroups mailing list, it seems @ghaering would like to pass the baton on being the maintainer. How is that going, and what seems to be the future outlook on this project?

**Comment by jameshiebert** [comment]
@rsvp I don't think there is any expected timeline unless someone takes on porting the C extension. For someone with Python C extension experience and sufficient motivation, it could probably be done in a day or two. However, that someone is not me. :)

**Comment by ghaering** [comment]
Trove classifier added.

**Comment by jameshiebert** [comment]
Cool, thanks!
