### ISSUE TITLE
Miliseconds are parsed as microseconds when loading timestamps

### ISSUE THREAD

**Issue by katastrofa999** [ghaering/pysqlite#74]
According to SQLite documentation, timestamps should be stored in SQLite databases as text in ISO format with miliseconds at the end after a dot, e.g.

    '2015-04-01 14:31:12.100'

(see https://www.sqlite.org/lang_datefunc.html). However, sqlite3 interprets the last three digits as the number of _microseconds_, leading to the bug below:

    import sqlite3
    import datetime
    con = sqlite3.connect(":memory:", detect_types=sqlite3.PARSE_DECLTYPES)
    con.execute("create table test (date timestamp)")
    date_in = datetime.datetime(2015, 4, 1, 14, 31, 12, 100000)
    con.execute("insert into test values('2015-04-01 14:31:12.100')")
    curs = con.cursor()
    curs.execute("select * from test")
    date_out = curs.fetchone()[0]
    assert date_in == date_out

(sqlite3 version 2.6.0)

A simple fix would be to change pysqlite/lib/dbapi2.py:

    microseconds = int(timepart_full[1])

to:

    if len(timepart_full[1]) == 6:
        microseconds = int(timepart_full[1])
    elif len(timepart_full[1]) == 3:
        microseconds = 1000 * int(timepart_full[1])
    else:
        # report an error

**Comment by katastrofa999** [comment]
Better solution:

    if len(timepart_full[1]) == 6:
        microseconds = int(timepart_full[1])
    else: # default to assuming that timestamp is formatted as required by SQLite docs: https://www.sqlite.org/lang_datefunc.html
        microseconds = 1000 * int(timepart_full[1])

I will submit that as a patch.

**Comment by ghaering** [comment]
This should be fixed by https://github.com/ghaering/pysqlite/commit/81c599f17d2369eeee87eb06dc6a6ef768d557a1 now.
