### ISSUE TITLE
setup.py egg_info fails when sphinx isn't present

### ISSUE THREAD

**Issue by rbtcollins** [ghaering/pysqlite#77]
Hi, I ran into a problem with pysqlite when testing some co-installability stuff with openstack's dependencies.

The issue is that python setup.py egg_info, which pip uses to determine what the install_requires for a package is, fails if sphinx isn't installed. Since you don't use setuptools pip is having to inject some nasty glue to get setuptools commands, but thats by-the-by :)

It looks to me like you want to build docs at sdist/install time- which is totally fine :). However, egg_info is neither sdist nor installation, and is needed to let pip get far enough along to actually try sdist/install.

There are a couple of patterns here, I don't know which is most appropriate for pysqlite, but here they are:
 - disable the docs if the deps are not present
 - use setuptools (its recommended everywhere now, I know of no reason not to use it), and export your dependencies via setup_requires

I suggest the latter one, since you refer folk to use easy-install to install sphinx; setuptools w/setup_requires will install sphinx just-in-time and then you can sanely use it.

**Comment by ghaering** [comment]
No actually I only want to build the docs myself to upload them. What is the exact command which triggers the problem for you? I can install pysqlite 2.6.3 via pip, and I do not have sphinx installed.

**Comment by rbtcollins** [comment]
You know, I didn't record the version or attach a trace - sorry!....  so it may have been fixed by your stopping using setuptools patch a ways back. Lets just close this.
