### ISSUE TITLE
Possible bug with Sqlite3.6.20

### ISSUE THREAD

**Issue by doomzhou** [ghaering/pysqlite#78]
Yesterday i write a small app with Flask and Sqlite3, but in product env(centos6.5) it's weird. I want to fix it.

### First I write a demo, ran it in Sqlite-3.6.20, Error below span text

>File "/opt/py343/lib/python3.4/sqlite3/dbapi2.py", line 67, in convert_timestamp

>datepart, timepart = val.split(b" ")

>ValueError: need more than 1 value to unpack

But in my archlinux that every packages are lastest(Sqlite 3.8.10.2 2015-05-20 18:17:19 2ef4f3a5b1d1d0c4338f8243d40a2452cc1f7fe4), I run it fine.

### Then I check the dbapi2.py(line66-77)

    def convert_timestamp(val):
        datepart, timepart = val.split(b" ")
        year, month, day = map(int, datepart.split(b"-"))
        timepart_full = timepart.split(b".")
        hours, minutes, seconds = map(int, timepart_full[0].split(b":"))
        if len(timepart_full) == 2:
            microseconds = int('{:0<6.6}'.format(timepart_full[1].decode()))
        else:
            microseconds = 0

        val = datetime.datetime(year, month, day, hours, minutes, seconds, microseconds)
        return val

It's a funcation, I think it's a py-sqlite's Bug with Sqlite-3.6.20．

[reference](http://stackoverflow.com/questions/31128103/possible-py-sqlite3-bug-with-version-3-6-20error-msgvalueerror-need-more-than)

**Comment by ghaering** [comment]
You better report this with the Python project. The Python 3 version of pysqlite is mainained *only* in the Python source tree.
