### ISSUE TITLE
multiple cursors

### ISSUE THREAD

**Issue by ilvalle** [ghaering/pysqlite#88]
In https://github.com/web2py/pydal we are facing an issue that can be described by the example below
```
import sqlite3
conn = sqlite3.connect(':memory:')

c1 = conn.cursor()
c2 = conn.cursor()

# Create table
c1.execute('''CREATE TABLE t0
             (qty real)''')
c1.execute('''CREATE TABLE t1
             (qty real)''')

for n in xrange(1, 100, 1):
    c1.execute("INSERT INTO t0 VALUES (%s)" % n)

# Save (commit) the changes
conn.commit()
c1.execute("select * from t0")

ctr=0
while True:
    # Get the next row in the cursor
    row = c1.fetchone()
    if row == None: break

    c2.execute("INSERT INTO t1 VALUES (999)")
    conn.commit()
    ctr += 1

print ctr
conn.close()
```
On python2.6, it prints 99, on all other versions return 101.
By committing out the ```conn.commit()``` in the loop, the problem disappear. 
Is it the correct behavior?

**Comment by ghaering** [comment]
The correct answer is 99. The issue on the Python bug tracker is http://bugs.python.org/issue10513

It was fixed in the pysqlite project in commit https://github.com/ghaering/pysqlite/commit/029050896b1e6058573abeef5a8970384c0c7faa
