### ISSUE TITLE
Support update_hook

### ISSUE THREAD

**Issue by sdementen** [ghaering/pysqlite#91]
Hello,

Would it be possible to add support of the update_hook function ?

Best alternative found on the web is not that user friendly http://stackoverflow.com/questions/16872700/sqlite-data-change-notification-callbacks-in-python-or-bash-or-cli/16920926#16920926

Seb

**Comment by ghaering** [comment]
Sounds like a reasonable feature to add.

**Comment by ghaering** [comment]
Superseded by #92
