### ISSUE TITLE
Wrap update_hook, commit_hook, rollback_hook and wal_hook

### ISSUE THREAD

**Issue by ghaering** [ghaering/pysqlite#92]

**Comment by coleifer** [comment]
If you all want this functionality, check out https://github.com/coleifer/sweepea -- it works with `pysqlite` / `sqlite3` from the standard lib and exposes additional functionality:

* https://sweepea.readthedocs.io/en/latest/api.html#Database.on_commit
* https://sweepea.readthedocs.io/en/latest/api.html#Database.on_update
* https://sweepea.readthedocs.io/en/latest/api.html#Database.on_rollback

**Comment by ghaering** [comment]
This project is feature complete and in maintenance-only mode, nothing new will be implemented here. Closing.
