### ISSUE TITLE
"sqlite3.h: No such file or directory" on python setup.py build_static

### ISSUE THREAD

**Issue by fillest** [ghaering/pysqlite#95]
I don't get how to build fresh static pysqlite+sqlite, is it documented somewhere? After some googling I found that I should manually fetch sqlite source code but building still fails:

```
$ wget http://sqlite.org/2016/sqlite-amalgamation-3110100.zip
...
$ unzip sqlite-amalgamation-3110100.zip 
Archive:  sqlite-amalgamation-3110100.zip
   creating: sqlite-amalgamation-3110100/
  inflating: sqlite-amalgamation-3110100/shell.c  
  inflating: sqlite-amalgamation-3110100/sqlite3.c  
  inflating: sqlite-amalgamation-3110100/sqlite3ext.h  
  inflating: sqlite-amalgamation-3110100/sqlite3.h  
$ python2.7 setup.py build_static
running build_static
running build_py
running build_ext
building 'pysqlite2._sqlite' extension
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DMODULE_NAME="pysqlite2.dbapi2" -DSQLITE_ENABLE_FTS3=1 -DSQLITE_ENABLE_FTS3_PARENTHESIS=1 -DSQLITE_ENABLE_FTS4=1 -DSQLITE_ENABLE_RTREE=1 -IPackage -Isqlite3 -Iwas -Inot -Ifound -Iin -Ithe -Ipkg-config -Isearch -Ipath. -IPerhaps -Iyou -Ishould -Iadd -Ithe -Idirectory -Icontaining -I`sqlite3.pc' -Ito -Ithe -IPKG_CONFIG_PATH -Ienvironment -Ivariable -INo -Ipackage -I'sqlite3' -Ifound -I/usr/include/python2.7 -c src/module.c -o build/temp.linux-x86_64-2.7/src/module.o
In file included from src/module.c:24:0:
src/connection.h:33:21: fatal error: sqlite3.h: No such file or directory
 #include "sqlite3.h"
                     ^
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

I tried to `mv sqlite-amalgamation-3110100/* .` or to rename the directory to `amalgamation` or to use virtualenv but it still fails.
This caught my attention in the build arguments:

```
-IPackage -Isqlite3 -Iwas -Inot -Ifound -Iin -Ithe -Ipkg-config -Isearch -Ipath. -IPerhaps -Iyou -Ishould -Iadd -Ithe -Idirectory -Icontaining -I`sqlite3.pc' -Ito -Ithe -IPKG_CONFIG_PATH -Ienvironment -Ivariable -INo -Ipackage -I'sqlite3' -Ifound
```

What does it mean?
I use Ubuntu 14.04.3

**Comment by ghaering** [comment]
The contents of the SQLite amagamition folder need to be moved into the pysqlite folder. I'll have to check if the docs are clear enough about this. Here's how I just did it:

➜  src cat build-static-pysqlite  
```
#!/bin/sh
git clone https://github.com/ghaering/pysqlite
cd pysqlite
wget https://www.sqlite.org/2016/sqlite-amalgamation-3110100.zip
unzip sqlite-amalgamation-3110100.zip
mv -i sqlite-amalgamation-3110100/* .
python2.7 setup.py build_static
```

**Comment by fillest** [comment]
As I wrote above, I did try to copy the files. I've just tried from scratch to run the commands you wrote and it still fails the same way.

**Comment by fillest** [comment]
I've just tried to run your snippet on a more clean Ubuntu server host. On the first attempt it failed the same way but I noted `-Ish: -I1: -Ipkg-config: -Inot -Ifound` in the printed build command. I installed `sudo apt-get install pkg-config` then run `build_static` and got the same `sqlite3.h: No such file or directory` again, with the same weird parameters `-IPackage -Isqlite3 -Iwas -Inot -Ifound -Iin -Ithe -Ipkg-config -Isearch -Ipath. -IPerhaps -Iyou -Ishould -Iadd -Ithe -Idirectory -Icontaining -I`sqlite3.pc' -Ito -Ithe -IPKG_CONFIG_PATH -Ienvironment -Ivariable -INo -Ipackage -I'sqlite3' -Ifound`

**Comment by w65l76** [comment]
This is because `setup.py` is trying to get the include and library path for the package sqlite3 even if we don't need the package to be installed as we copied amalgamation to the build folder.

To fix it, in the build folder create file named `setup-patch` with the following contents
```
146a147,149
>             ext.include_dirs.append(".")
>             build_ext.build_extension(self, ext)
>             return
```
Then run `patch setup.py setup-patch`

After that `python setup.py build_static` should work

**Comment by ghaering** [comment]
Not a bug in the project.

**Comment by bencaine1** [comment]
In case this is helpful for anyone else: In order to get this to work, I had to run

`python2.7 setup.py build_static install`

instead of

`python2.7 setup.py build_static`

And I didn't need to do the setup-patch thing.
